### PR TITLE
Add support for diamond

### PR DESCRIPTION
**Pull request by urmi-21**
I have added a function *strata_diamond* to use diamond blastp instead of ncbi blastp. I have tested the changes locally and also added a small unit test.
To use diamond instead of blast user can directly use the function `strata_diamond` instead of `strata_blast` and diamond must be present in the path. Right now I have coded diamond to run in `--more-sensitive` mode. Perhaps in future the function could be made more flexible to take modes as parameters.

### CODE REVIEW

**Comment by arendsee** [comment]
@urmi-21 Thanks for the pull request! The check is failing on Travis. Does everything pass locally?

**Comment by urmi-21** [comment]
@arendsee Everything passed locally. I think travis doesn't know where to find Diamond and that is failing the test.

**Comment by urmi-21** [comment]
testthat seems to pass with warnings

**Comment by arendsee** [comment]
@urmi-21 I looked over the check results and it seems a documentation issue is raising the warning. I've seen this exact issue many times before, so I'll accept the PR and then fix the documentation issue myself.

**Pull request merged**
